# Generated by Django 4.0.4 on 2022-06-05 07:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationModel',
            fields=[
                ('cpns_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='赔偿方案编号')),
                ('cpns_category', models.IntegerField(choices=[(1, 'N'), (2, 'N1'), (3, 'N2')], default=1, verbose_name='赔偿方案分类')),
                ('cpns_content', ckeditor.fields.RichTextField(blank=True, verbose_name='赔偿方案内容')),
                ('activated', models.IntegerField(choices=[(0, '未激活'), (1, '已激活')], default=1, verbose_name='数据状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Compensation',
                'verbose_name_plural': 'Compensations',
                'db_table': 'compensation',
                'ordering': ['-update_at'],
                'managed': True,
            },
        ),
    ]
