# Generated by Django 4.0.4 on 2022-05-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'managed': True, 'ordering': ['-update_at'], 'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
    ]
