# Generated by Django 4.0.4 on 2022-05-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0002_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'managed': True, 'ordering': ['-update_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
    ]
