# Generated by Django 4.0.4 on 2022-05-06 06:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0004_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='activated',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '已激活')], default=1, verbose_name='数据状态'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='art_source',
            field=models.IntegerField(choices=[(1, '自撰'), (2, '转载')], default=2, verbose_name='文章来源'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_category',
            field=models.IntegerField(choices=[(1, '莫慌'), (2, '别闹')], default=1, verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_declaration',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='文章声明'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_status',
            field=models.IntegerField(choices=[(1, '未发布'), (2, '已发布')], default=1, verbose_name='文章状态'),
        ),
    ]
