# Generated by Django 4.0.4 on 2022-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0005_articlemodel_activated_articlemodel_art_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='art_publish_time',
            field=models.DateTimeField(blank=True, default='2017-06-13 18:00:00', verbose_name='文章发布时间'),
            preserve_default=False,
        ),
    ]
