# Generated by Django 4.0.4 on 2022-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0006_articlemodel_art_publish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='art_publish_time',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='publish_time',
            field=models.DateTimeField(blank=True, default='2017-06-13 18:00:00', verbose_name='发表时间'),
            preserve_default=False,
        ),
    ]
