# Generated by Django 4.0.4 on 2022-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0007_remove_articlemodel_art_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='art_publisher',
            field=models.CharField(blank=True, max_length=32, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_thumbnail',
            field=models.CharField(blank=True, max_length=128, verbose_name='缩略图'),
        ),
    ]
