# Generated by Django 4.0.4 on 2022-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worry', '0008_alter_articlemodel_art_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='art_illustrated',
            field=models.CharField(blank=True, max_length=256, verbose_name='文章插图'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_publisher',
            field=models.CharField(blank=True, max_length=64, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='art_title',
            field=models.CharField(blank=True, max_length=128, verbose_name='文章标题'),
        ),
    ]
